import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://inghamsv2-ecms.qa.hotelplan.co.uk/');
  await page.getByRole('button', { name: 'Ski' }).click();
  await page.getByRole('button', { name: 'Search holidays' }).click();
  await expect(page.locator('#searchResult div').filter({ hasText: '3Residence La Riviere' }).nth(1)).toBeVisible();
  await page.locator('div').filter({ hasText: /^View results by resort$/ }).locator('label').click();
  await expect(page.locator('#searchResult div').filter({ hasText: 'ChamonixFranceFantastic off' }).nth(2)).toBeVisible();
  await page.getByRole('button', { name: 'Ratings' }).click();
  await page.locator('label').filter({ hasText: /^1$/ }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('No results matching your')).toBeVisible();
  await page.getByRole('button', { name: 'Ratings' }).click();
  await page.locator('label').filter({ hasText: /^1$/ }).getByRole('img').click();
  await page.locator('label').filter({ hasText: '1.5' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('No results matching your')).toBeVisible();
  await page.getByRole('button', { name: 'Ratings' }).click();
  await page.locator('label').filter({ hasText: '1.5' }).click();
  await page.locator('label').filter({ hasText: /^2$/ }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.locator('#searchResult div').filter({ hasText: 'Offers availableCourchevelThree Valleys Ski Area, France600km of marked' }).nth(2)).toBeVisible();
  await page.getByRole('button', { name: 'View Accommodation' }).click();
  await expect(page.locator('#searchResult div').filter({ hasText: '2Hotel Olympic (1850)' }).nth(1)).toBeVisible();
  await page.locator('div').filter({ hasText: /^View results by resort$/ }).locator('label').click();
  await page.getByRole('button', { name: 'Ratings' }).click();
  await page.locator('label').filter({ hasText: /^2$/ }).getByRole('img').click();
  await page.locator('label').filter({ hasText: '2.5' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.locator('.c-search-card--destinations-footer > button').first().click();
  await expect(page.locator('#searchResult div').filter({ hasText: '2.5Hameau du Borsat' }).nth(1)).toBeVisible();
  await page.locator('div').filter({ hasText: /^View results by resort$/ }).locator('label').click();
  await page.getByRole('button', { name: 'Ratings' }).click();
  await page.locator('label').filter({ hasText: '2.5' }).getByRole('img').click();
  await page.locator('label').filter({ hasText: /^3$/ }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.locator('#searchResult div').filter({ hasText: 'ChamonixFranceFantastic off' }).nth(2)).toBeVisible();
  await page.locator('.c-search-card--destinations-footer > button').first().click();
  await expect(page.locator('#searchResult div').filter({ hasText: '3Residence La Riviere' }).nth(1)).toBeVisible();
});