import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://inghamsv2-ecms.qa.hotelplan.co.uk/');
  await page.getByRole('button', { name: 'Ski' }).click();
  await page.getByRole('button', { name: 'Search holidays' }).click();
  await page.getByRole('button', { name: 'Budget' }).click();
  await expect(page.locator('.c-modal__body')).toBeVisible();
  await page.locator('#minInputField').click();
  await page.locator('#minInputField').fill('-1');
  await page.locator('#minInputField').press('Enter');
  await expect(page.locator('div').filter({ hasText: /^£$/ }).first()).toBeVisible();
  await page.locator('#maxInputField').click();
  await page.locator('#maxInputField').fill('999999999999999999999999999999999999');
  await page.locator('#maxInputField').press('Enter');
  await expect(page.locator('div').filter({ hasText: /^£$/ }).nth(1)).toBeVisible();
  await page.locator('#maxInputField').click();
  await page.locator('#maxInputField').fill('0');
  await page.locator('#maxInputField').press('Enter');
  await expect(page.locator('div').filter({ hasText: /^£$/ }).nth(1)).toBeVisible();
  await page.locator('#maxInputField').click();
  await page.locator('#maxInputField').fill('10');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('No results matching your')).toBeVisible();
  await page.getByRole('button', { name: 'Budget' }).click();
  await page.locator('#minInputField').click();
  await page.locator('#minInputField').fill('100');
  await page.locator('#maxInputField').click();
  await page.locator('#maxInputField').fill('5000');
  await page.locator('#maxInputField').press('Enter');
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('£449pp')).toBeVisible();
  await expect(page.getByText('£492pp')).toBeVisible();
  await expect(page.getByText('£499pp')).toBeVisible();
  await page.getByRole('button', { name: 'Budget' }).click();
  await page.locator('.c-range-slider__thumb').first().click();
  await page.locator('.c-range-slider__thumb').first().click();
  await page.locator('.c-range-slider > div:nth-child(4)').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByText('£449pp')).toBeVisible();
});