export default{
    ci:{
        prefix:'',
        suffix:''
    },
    dev:{
        inghams:'https://inghams-v2.newdev.hotelplan.co.uk',
        e_cms:'https://localhost:44340',
        p_cms:'https://localhost:44361',
    },
    dev_test:{
        inghams:'https://inghams-v2.newdev.hotelplan.co.uk',
        e_cms:'https://inghams-v2.newdev.hotelplan.co.uk',
        p_cms:'https://inghams-product-cms.newdev.hotelplan.co.uk',
    },
    qa:{
        inghams:'https://inghams-v2.qa.hotelplan.co.uk',
        e_cms:'https://inghamsv2-ecms.qa.hotelplan.co.uk',
        p_cms:'https://inghamsv2-pcms.qa.hotelplan.co.uk',

        en_gb:'https://dev-feature.explore.co.uk/',
        en_us:'https://www.exploreworldwide.com/',
        en_au:'https://www.exploreworldwide.com.au/',
        en_nz:'https://www.exploreworldwide.co.nz/',
        en_ca:'https://www.exploreworldwide.ca/',
        en_eu:'https://www.exploreworldwide.eu/',
        en_ch:'https://www.exploreworldwide.ch/',
    },
    stg:{
        inghams:'https://inghams-v2.stg.hotelplan.co.uk',
        e_cms:'https://inghamsv2-ecms.stg.hotelplan.co.uk',
        p_cms:'https://inghamsv2-pcms.stg.hotelplan.co.uk',
    },
    prod:{
        inghams:'https://www.inghams.co.uk',
        e_cms:'https://inghamsv2-ecms.hotelplan.co.uk',
        p_cms:'https://inghamsv2-pcms.hotelplan.co.uk',
    },
};