import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://chox.test.hotelplan.co.uk/?ProgramCode=GBINA&From=LGW&To=FRVD&Property=FRVD0138ACC&Room=A1&Board=HB&When=2024-12-21&Nights=7&Adults=2&Children=0&Childage=&BrandCode=INGH&CatalogueCode=010&CurrencyCode=GBP');
  await expect(page.getByRole('heading', { name: 'Finding your holiday...' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Your holiday' })).toBeVisible();
  await expect(page.getByText('Hotel Ducs de Savoie, Val d\'IsereVal d\'Isère, France2 adults (7 nights)Travel Outbound - 21/12/2024 Return - 28/12/2024rooms1st Floor, Room 102 Double - Halfboard (Bath, WC, Balcony) Travel and rooms subtotal£2,938.00Deposit£300.00per person£1,469.00Total£')).toBeVisible({timeout:60000});
  await expect(page.locator('.c-room-list > .c-card--inner')).toBeVisible();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#passenger-1-1-title').selectOption('mr');
  await page.locator('#passenger-1-3-firstName').click();
  await page.locator('#passenger-1-3-firstName').fill('Test One');
  await page.locator('#passenger-1-4-lastName').click();
  await page.locator('#passenger-1-4-lastName').fill('Guest');

  await page.locator('form div').filter({ hasText: 'Adult 1 (lead passenger)Title' }).getByRole('combobox').nth(2).selectOption('01');
  await page.locator('form div').filter({ hasText: 'Adult 1 (lead passenger)Title' }).getByRole('combobox').nth(3).selectOption('2000');
  await page.getByPlaceholder('Start typing').click();
  await page.getByPlaceholder('Start typing').fill('1st ');
  await page.getByRole('link', { name: 'South Terrace Ballinlough, T12 Cork' }).click();
  await page.getByLabel('Phone number (mobile').click();
  await page.getByLabel('Phone number (mobile').fill('1234567890');
  await page.locator('input[name="customer-email"]').click();
  await page.locator('input[name="customer-email"]').fill('test@email.com');
  await page.getByLabel('Confirm e-mail address *').click();
  await page.getByLabel('Confirm e-mail address *').fill('test@email.com');
  await page.locator('#passenger-2-1-title').selectOption('ms');
  await page.locator('#passenger-2-3-firstName').click();
  await page.locator('#passenger-2-3-firstName').fill('Guest Two');
  await page.locator('#passenger-2-4-lastName').click();
  await page.locator('#passenger-2-4-lastName').fill('Test');
  
  await page.locator('form div').filter({ hasText: 'Adult 2 Title *' }).getByRole('combobox').nth(2).selectOption('02');
  await page.locator('form div').filter({ hasText: 'Adult 2 Title *' }).getByRole('combobox').nth(3).selectOption('2001');
  await page.locator('form div').filter({ hasText: 'Emergency contact' }).locator('#customer-number').click();
  await page.locator('form div').filter({ hasText: 'Emergency contact' }).locator('#customer-number').fill('1234567890');
  await page.getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('heading', { name: 'Finding your holiday...' })).toBeVisible();
  await page.goto('https://chox.test.hotelplan.co.uk/passenger-details');
  await page.goto('https://chox.test.hotelplan.co.uk/checkout');
  await expect(page.getByRole('heading', { name: 'Payment', exact: true })).toBeVisible();
  await expect(page.getByText('Hotel Ducs de Savoie, Val d\'IsereVal d\'Isère, France2 adults (7 nights)Travel Outbound - 21/12/2024 Return - 28/12/2024rooms1st Floor, Room 102 Double - Halfboard (Bath, WC, Balcony) Travel and rooms subtotal£2,938.00Deposit£300.00per person£1,469.00Total£')).toBeVisible();
  await page.locator('#selectCard').selectOption('1-visa');
  await page.getByLabel('Please confirm that you have').check();
  await page.getByRole('button', { name: 'Confirm and pay' }).click();
  await expect(page.locator('.c-modal__body')).toBeVisible();
  await page.frameLocator('#cashier-modal').locator('#creditCardHolder').click();
  await page.frameLocator('#cashier-modal').locator('#creditCardHolder').fill('test user');
  await page.frameLocator('#cashier-modal').locator('#KKnr').click();
  await page.frameLocator('#cashier-modal').locator('#KKnr').fill('4111111111111111');
  await page.frameLocator('#cashier-modal').locator('#s2id_autogen3').getByRole('link').click();
  await page.frameLocator('#cashier-modal').getByRole('option', { name: '03' }).click();
  await page.frameLocator('#cashier-modal').locator('#s2id_autogen5').getByRole('link').click();
  await page.frameLocator('#cashier-modal').getByRole('option', { name: '2030' }).click();
  await page.frameLocator('#cashier-modal').locator('input[name="cccvc"]').click();
  await page.frameLocator('#cashier-modal').locator('input[name="cccvc"]').fill('234');
  await page.frameLocator('#cashier-modal').getByRole('button', { name: 'Confirm' }).click();
  await expect(page.frameLocator('#cashier-modal').getByRole('img', { name: 'Failure' })).toBeVisible();
  await page.getByRole('button', { name: 'Close' }).click();
});