name: Hotel-Plan-Test-Workflow

run-name: HP ${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }} Test Run Build ${{github.run_number}} - ${{ github.event.inputs.environment || github.event.client_payload.environment || inputs.environment }}

on:
  workflow_call:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: string
      scope:
        description: 'Test Suites / Test Scope'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: true
        default: 'INFO'
        type: choice
        options:
        - INFO
        - DEBUG
        - TRACE
      environment:
        description: 'Environment'
        required: true
        default: 'qa'
        type: choice
        options:
        - qa
        - stg
      scope:
        description: 'Test Suites / Test Scope'
        required: true
        default: 'Components'
        type: choice
        options:
        - Search Migration
        - Migration
        - Components
        - Search
        - Accommodation Pages

  repository_dispatch:
    types: [deploy]

jobs:
  HP_Test_Run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Set environment variable
      run: echo "ENV=${{ github.event.inputs.environment || github.event.client_payload.environment || inputs.environment }}" >> $GITHUB_ENV

    - name: Run Playwright tests
      env:
        ECMS_USERNAME: ${{ secrets.ECMS_USERNAME_QA }}
        ECMS_PASSWORD: ${{ secrets.ECMS_PASSWORD_QA }}
        PCMS_USERNAME: ${{ secrets.PCMS_USERNAME_QA }}
        PCMS_PASSWORD: ${{ secrets.PCMS_PASSWORD_QA }}
      run: |  

        if [ "${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}" == "Search Migration" ]; then
          npx playwright test tests/e2e_tests/inw_migration_tests/search/ --project=Chromium
        elif [ "${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}" == "Migration" ]; then
          npx playwright test tests/e2e_tests/inw_migration_tests/ --project=Chromium
        elif [ "${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}" == "Components" ]; then
          npx playwright test tests/e2e_tests/inw_tests/components/ --project=Chromium --workers=3 --max-failures=5
        elif [ "${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}" == "Search" ]; then
          npx playwright test tests/e2e_tests/inw_tests/search/ --project=Chromium
        elif [ "${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}" == "Accommodation Pages" ]; then
          npx playwright test tests/e2e_tests/inw_tests/accomodation_pages/ --project=Chromium
        else
          echo "No matching scope found. Please check the input."
          exit 1
        fi

    - name: Generate Allure Report
      if: ${{ !cancelled() }}
      run: |
        npx allure generate allure-results --clean -o allure-report

    - name: Deploy Allure Report to GitHub Pages
      if: ${{ !cancelled() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        destination_dir: reports/${{ github.run_number }}
        keep_files: true

    - name: Create Report Link Comment
      if: ${{ !cancelled() }}
      uses: actions/github-script@v7
      with:
        script: |
          const reportUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/reports/${{ github.run_number }}/`;
          const scope = '${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}';
          const environment = '${{ github.event.inputs.environment || github.event.client_payload.environment || inputs.environment }}';
          const runNumber = '${{ github.run_number }}';
          
          const comment = `## 📊 Allure Test Report
          
          **Test Run Details:**
          - Scope: ${scope}
          - Environment: ${environment}
          - Build: ${runNumber}
          
          📋 **[View Allure Report](${reportUrl})**
          
          _Report generated on: ${new Date().toLocaleString()}_`;
          
          // Create a commit status with the report link
          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            target_url: reportUrl,
            description: `Allure Report - ${scope} (${environment})`,
            context: 'Test Report'
          });
          
          // Add the report URL to the workflow summary
          await core.summary
            .addHeading('📊 Allure Test Report', 2)
            .addTable([
              [{data: 'Scope', header: true}, {data: 'Environment', header: true}, {data: 'Build', header: true}],
              [scope, environment, runNumber]
            ])
            .addSeparator()
            .addRaw(`🔗 <a href="${reportUrl}"><strong>View Allure Report</strong></a>`)
            .addSeparator()
            .addRaw(`<small><em>Report generated on: ${new Date().toLocaleString()}</em></small>`)
            .write();
          
          console.log(`📊 Allure Report available at: ${reportUrl}`);

    - name: Test Report Generation
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: HP_${{ github.event.inputs.scope || github.event.client_payload.scope || inputs.scope }}_Test_Results_${{github.run_number}} - ${{ github.event.inputs.environment || github.event.client_payload.environment || inputs.environment }}
        path: |
          test-results/*
          allure-report/*