name: Hotel-Plan-Test-Workflow-Scheduled-Regression
run-name: HP Scheduled Regression Test Run Build ${{github.run_number}}

on:
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 0 * * 1'
#    - cron: '0 0 * * 2'

jobs:
  HP_Test_Run_Scheduled_Regression_Dev:
    if: github.event.schedule == '0 0 * * 0'
    uses: ./.github/workflows/main-workflow.yml
    with:
      logLevel: 'DEBUG'
      environment: 'qa'
      scope: 'Regression'
  HP_Test_Run_Scheduled_Regression_Staging:
    if: github.event.schedule == '0 0 * * 1'
    uses: ./.github/workflows/main-workflow.yml
    with:
      logLevel: 'DEBUG'
      environment: 'stg'
      scope: 'Regression'
  HP_Test_Run_Scheduled_Regression_Production:
    if: github.event.schedule == '0 0 * * 2'
    uses: ./.github/workflows/main-workflow.yml
    with:
      logLevel: 'DEBUG'
      environment: 'prod'
      scope: 'Regression'

